-- MySQL Script generated by MySQL Workbench
-- Wed Aug 19 11:06:18 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_categorias` (
  `id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` ENUM('receita', 'despesa') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TB_categorias_TB_usuarios_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_categorias_TB_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`TB_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_transacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_transacoes` (
  `id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TB_transacoes_TB_categorias1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_TB_transacoes_TB_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_TB_transacoes_TB_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`TB_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_transacoes_TB_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`TB_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
